"""added article types

Revision ID: 4e07988e2d7c
Revises: None
Create Date: 2015-12-18 11:59:37.642457

"""

# revision identifiers, used by Alembic.
revision = '4e07988e2d7c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'article_types', ['type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'type_id')
    op.drop_table('article_types')
    ### end Alembic commands ###
